/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserListIndexRouteImport } from './routes/user/list/index'

const rootRouteImport = createRootRoute()

const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserListIndexRoute = UserListIndexRouteImport.update({
  id: '/user/list/',
  path: '/user/list/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/user': typeof UserIndexRoute
  '/user/list': typeof UserListIndexRoute
}
export interface FileRoutesByTo {
  '/user': typeof UserIndexRoute
  '/user/list': typeof UserListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/user/': typeof UserIndexRoute
  '/user/list/': typeof UserListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/user' | '/user/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/user' | '/user/list'
  id: '__root__' | '/user/' | '/user/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserListIndexRoute: typeof UserListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/list/': {
      id: '/user/list/'
      path: '/user/list'
      fullPath: '/user/list'
      preLoaderRoute: typeof UserListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserListIndexRoute: UserListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
